Add avatar component
inputlogic/elements pull request #17
Opened 2018-12-13 00:01 UTC by coryschadt

2019-01-04 21:59 UTC, staydecent commented on components/avatar/index.js
> +export default ({
Anonymous components should be avoided as they show up as `<undefined ... />` in debuggers and tests. You can use implicitly named arrow functions however:

```jsx
const Avatar = () => /* ... */
export default Avatar
```

Or you could use an explcitly named function:

```jsx
export default function Avatar () {
  /* ... */
}
```

2019-01-04 21:59 UTC, staydecent commented on components/avatar/index.js
> +  </div>
I think you forgot the `import './style.less`

2019-01-04 22:01 UTC, staydecent commented on components/avatar/package.json
> +  "description": "",
Could you add a short description?

2019-01-04 22:02 UTC, staydecent requested changes
Needs a few changes, but this will be a great addition to the repo!

2019-01-08 17:26 UTC, coryschadt commented
Hey @staydecent,  Thanks for reviewing.

I have made these changes. Can you review and let me know?

Cheers

2019-01-10 21:50 UTC, staydecent approved these changes
💎

2019-01-10 21:50 UTC, merged